### ISSUE TITLE
about paper and dataset

### ISSUE THREAD

**Issue by jun0wanan** [liveseongho/DramaQA#1]
hi,

      What the difference between this repo and https://github.com/liveseongho/DramaQAChallenge2020 ?  (●'◡'●)

jun
2.28

**Comment by liveseongho** [comment]
DramaQAChallenge2020 was used for the DramaQA Challenge of last year. After then, we revised our code for the submitted [paper](https://arxiv.org/abs/2005.03356) and future work. I highly recommend you to use this repository for your work! Thank you.
